### ISSUE TITLE
how to implement the project

### ISSUE THREAD

**Issue by wangguojun2018** [tj27-vkr/RCNN-Vehicle-Tracking-Lane-Detection#2]
Dear author:
  I am new learner for programming. I want to implement the project, but I don not know what software environment this project needs. Now , I installed python and other modules by anaconda .When I run main.py, there's a wrong hint. Could you tell me what software and hardware environment  I need. Do I need GPU?
![tim 20180207165333](https://user-images.githubusercontent.com/36224780/35906973-75d5c00e-0c27-11e8-9b93-e8a442d748c8.jpg)

**Comment by tj27-vkr** [comment]
This is a problem faced with the installation of PIL library. Try installing PIL version '4.2.1'
